server:
  port: 9999

spring:
  application:
    name: tj-java-sdk


# 自定义数据
peer:
  #  pubKey: ENC(q2jN0qmIz9C9s5qfCJhR/p2Yyi0anT9wwAhEkHIae1kaRIWwww5mWbQ3FewvtQlVVYX0Z7ZuWcufDnz2OpXAlL6e0X9ANFZy9F9M9waBoioMBUqx9krgUf/z1W31XeUJydh1itaQvm6ECYwJuUOLaUQW1pc9bd7ZKSd0cuTNlAIabWTMqPs3uerbJjJPIjd7)
  pubKey: 2c7f6f353d828e99692bb8bf960186f218674581495b399db753c00dd636c4f0583f7a833ce67d352e7d32be5d6e3fc899d7004efe1f450fc1a078ee856a8b75
  #  pubKey: 7408b0d5577d5be240afbf0712397e5b19df9213f4d7c2cfa98d0d545fa9fc013a2a8fc4046c62e4b8fc00c524a92cd66d54cd2fc8c88c834d06ba7a951eea73
  privateKey: -----BEGIN PRIVATE KEY-----
    MIGTAgEAMBMGByqGSM49AgEGCCqBHM9VAYItBHkwdwIBAQQgYAQKDYyBqB8Ywsnz
    2Gz7zZAU2aQYo0QdQO/ltOQeWcCgCgYIKoEcz1UBgi2hRANCAARbhMHt+g85lja5
    MDwEp9WidHMVWM/Dg9bEdd1aE8qrUfVzzz7GhrMV6JHfs7/VO9TO9YTw3czuYm/s
    QmiRJ+Vs
    -----END PRIVATE KEY-----
  ip: 10.1.3.150
  port: 9008

#盐
jasypt:
  encryptor:
    password: tjfocvDz7oJn6