// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package chain.tj.model.proto;

public final class MyTransaction {
    private MyTransaction() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface TransactionHeaderOrBuilder extends
            // @@protoc_insertion_point(interface_extends:transaction.TransactionHeader)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional uint32 version = 1;</code>
         */
        int getVersion();

        /**
         * <code>optional uint32 type = 2;</code>
         */
        int getType();

        /**
         * <code>optional uint32 subType = 3;</code>
         */
        int getSubType();

        /**
         * <code>optional uint64 timestamp = 4;</code>
         */
        long getTimestamp();

        /**
         * <code>optional bytes transactionHash = 5;</code>
         */
        com.google.protobuf.ByteString getTransactionHash();
    }

    /**
     * Protobuf type {@code transaction.TransactionHeader}
     */
    public static final class TransactionHeader extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:transaction.TransactionHeader)
            TransactionHeaderOrBuilder {
        // Use TransactionHeader.newBuilder() to construct.
        private TransactionHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TransactionHeader() {
            version_ = 0;
            type_ = 0;
            subType_ = 0;
            timestamp_ = 0L;
            transactionHash_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private TransactionHeader(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            version_ = input.readUInt32();
                            break;
                        }
                        case 16: {

                            type_ = input.readUInt32();
                            break;
                        }
                        case 24: {

                            subType_ = input.readUInt32();
                            break;
                        }
                        case 32: {

                            timestamp_ = input.readUInt64();
                            break;
                        }
                        case 42: {

                            transactionHash_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return chain.tj.model.proto.MyTransaction.internal_static_transaction_TransactionHeader_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return chain.tj.model.proto.MyTransaction.internal_static_transaction_TransactionHeader_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            chain.tj.model.proto.MyTransaction.TransactionHeader.class, chain.tj.model.proto.MyTransaction.TransactionHeader.Builder.class);
        }

        public static final int VERSION_FIELD_NUMBER = 1;
        private int version_;

        /**
         * <code>optional uint32 version = 1;</code>
         */
        public int getVersion() {
            return version_;
        }

        public static final int TYPE_FIELD_NUMBER = 2;
        private int type_;

        /**
         * <code>optional uint32 type = 2;</code>
         */
        public int getType() {
            return type_;
        }

        public static final int SUBTYPE_FIELD_NUMBER = 3;
        private int subType_;

        /**
         * <code>optional uint32 subType = 3;</code>
         */
        public int getSubType() {
            return subType_;
        }

        public static final int TIMESTAMP_FIELD_NUMBER = 4;
        private long timestamp_;

        /**
         * <code>optional uint64 timestamp = 4;</code>
         */
        public long getTimestamp() {
            return timestamp_;
        }

        public static final int TRANSACTIONHASH_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString transactionHash_;

        /**
         * <code>optional bytes transactionHash = 5;</code>
         */
        public com.google.protobuf.ByteString getTransactionHash() {
            return transactionHash_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (version_ != 0) {
                output.writeUInt32(1, version_);
            }
            if (type_ != 0) {
                output.writeUInt32(2, type_);
            }
            if (subType_ != 0) {
                output.writeUInt32(3, subType_);
            }
            if (timestamp_ != 0L) {
                output.writeUInt64(4, timestamp_);
            }
            if (!transactionHash_.isEmpty()) {
                output.writeBytes(5, transactionHash_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (version_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, version_);
            }
            if (type_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, type_);
            }
            if (subType_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, subType_);
            }
            if (timestamp_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt64Size(4, timestamp_);
            }
            if (!transactionHash_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, transactionHash_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof chain.tj.model.proto.MyTransaction.TransactionHeader)) {
                return super.equals(obj);
            }
            chain.tj.model.proto.MyTransaction.TransactionHeader other = (chain.tj.model.proto.MyTransaction.TransactionHeader) obj;

            boolean result = true;
            result = result && (getVersion()
                    == other.getVersion());
            result = result && (getType()
                    == other.getType());
            result = result && (getSubType()
                    == other.getSubType());
            result = result && (getTimestamp()
                    == other.getTimestamp());
            result = result && getTransactionHash()
                    .equals(other.getTransactionHash());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            hash = (37 * hash) + VERSION_FIELD_NUMBER;
            hash = (53 * hash) + getVersion();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType();
            hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
            hash = (53 * hash) + getSubType();
            hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getTimestamp());
            hash = (37 * hash) + TRANSACTIONHASH_FIELD_NUMBER;
            hash = (53 * hash) + getTransactionHash().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(chain.tj.model.proto.MyTransaction.TransactionHeader prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code transaction.TransactionHeader}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:transaction.TransactionHeader)
                chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_TransactionHeader_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_TransactionHeader_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                chain.tj.model.proto.MyTransaction.TransactionHeader.class, chain.tj.model.proto.MyTransaction.TransactionHeader.Builder.class);
            }

            // Construct using chain.tj.model.proto.MyTransaction.TransactionHeader.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                version_ = 0;

                type_ = 0;

                subType_ = 0;

                timestamp_ = 0L;

                transactionHash_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_TransactionHeader_descriptor;
            }

            public chain.tj.model.proto.MyTransaction.TransactionHeader getDefaultInstanceForType() {
                return chain.tj.model.proto.MyTransaction.TransactionHeader.getDefaultInstance();
            }

            public chain.tj.model.proto.MyTransaction.TransactionHeader build() {
                chain.tj.model.proto.MyTransaction.TransactionHeader result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public chain.tj.model.proto.MyTransaction.TransactionHeader buildPartial() {
                chain.tj.model.proto.MyTransaction.TransactionHeader result = new chain.tj.model.proto.MyTransaction.TransactionHeader(this);
                result.version_ = version_;
                result.type_ = type_;
                result.subType_ = subType_;
                result.timestamp_ = timestamp_;
                result.transactionHash_ = transactionHash_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof chain.tj.model.proto.MyTransaction.TransactionHeader) {
                    return mergeFrom((chain.tj.model.proto.MyTransaction.TransactionHeader) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(chain.tj.model.proto.MyTransaction.TransactionHeader other) {
                if (other == chain.tj.model.proto.MyTransaction.TransactionHeader.getDefaultInstance()) return this;
                if (other.getVersion() != 0) {
                    setVersion(other.getVersion());
                }
                if (other.getType() != 0) {
                    setType(other.getType());
                }
                if (other.getSubType() != 0) {
                    setSubType(other.getSubType());
                }
                if (other.getTimestamp() != 0L) {
                    setTimestamp(other.getTimestamp());
                }
                if (other.getTransactionHash() != com.google.protobuf.ByteString.EMPTY) {
                    setTransactionHash(other.getTransactionHash());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                chain.tj.model.proto.MyTransaction.TransactionHeader parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (chain.tj.model.proto.MyTransaction.TransactionHeader) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int version_;

            /**
             * <code>optional uint32 version = 1;</code>
             */
            public int getVersion() {
                return version_;
            }

            /**
             * <code>optional uint32 version = 1;</code>
             */
            public Builder setVersion(int value) {

                version_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 version = 1;</code>
             */
            public Builder clearVersion() {

                version_ = 0;
                onChanged();
                return this;
            }

            private int type_;

            /**
             * <code>optional uint32 type = 2;</code>
             */
            public int getType() {
                return type_;
            }

            /**
             * <code>optional uint32 type = 2;</code>
             */
            public Builder setType(int value) {

                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 type = 2;</code>
             */
            public Builder clearType() {

                type_ = 0;
                onChanged();
                return this;
            }

            private int subType_;

            /**
             * <code>optional uint32 subType = 3;</code>
             */
            public int getSubType() {
                return subType_;
            }

            /**
             * <code>optional uint32 subType = 3;</code>
             */
            public Builder setSubType(int value) {

                subType_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 subType = 3;</code>
             */
            public Builder clearSubType() {

                subType_ = 0;
                onChanged();
                return this;
            }

            private long timestamp_;

            /**
             * <code>optional uint64 timestamp = 4;</code>
             */
            public long getTimestamp() {
                return timestamp_;
            }

            /**
             * <code>optional uint64 timestamp = 4;</code>
             */
            public Builder setTimestamp(long value) {

                timestamp_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint64 timestamp = 4;</code>
             */
            public Builder clearTimestamp() {

                timestamp_ = 0L;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString transactionHash_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes transactionHash = 5;</code>
             */
            public com.google.protobuf.ByteString getTransactionHash() {
                return transactionHash_;
            }

            /**
             * <code>optional bytes transactionHash = 5;</code>
             */
            public Builder setTransactionHash(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                transactionHash_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes transactionHash = 5;</code>
             */
            public Builder clearTransactionHash() {

                transactionHash_ = getDefaultInstance().getTransactionHash();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:transaction.TransactionHeader)
        }

        // @@protoc_insertion_point(class_scope:transaction.TransactionHeader)
        private static final chain.tj.model.proto.MyTransaction.TransactionHeader DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new chain.tj.model.proto.MyTransaction.TransactionHeader();
        }

        public static chain.tj.model.proto.MyTransaction.TransactionHeader getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<TransactionHeader>
                PARSER = new com.google.protobuf.AbstractParser<TransactionHeader>() {
            public TransactionHeader parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TransactionHeader(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<TransactionHeader> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TransactionHeader> getParserForType() {
            return PARSER;
        }

        public chain.tj.model.proto.MyTransaction.TransactionHeader getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface TransactionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:transaction.Transaction)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        boolean hasHeader();

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        chain.tj.model.proto.MyTransaction.TransactionHeader getHeader();

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder getHeaderOrBuilder();

        /**
         * <pre>
         * 交易内容
         * </pre>
         *
         * <code>optional bytes data = 2;</code>
         */
        com.google.protobuf.ByteString getData();

        /**
         * <pre>
         * 发送方公钥
         * </pre>
         *
         * <code>optional bytes pubkey = 3;</code>
         */
        com.google.protobuf.ByteString getPubkey();

        /**
         * <pre>
         * 签名
         * </pre>
         *
         * <code>optional bytes sign = 4;</code>
         */
        com.google.protobuf.ByteString getSign();

        /**
         * <code>optional bytes result = 5;</code>
         */
        com.google.protobuf.ByteString getResult();

        /**
         * <code>optional bytes extra = 6;</code>
         */
        com.google.protobuf.ByteString getExtra();
    }

    /**
     * Protobuf type {@code transaction.Transaction}
     */
    public static final class Transaction extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:transaction.Transaction)
            TransactionOrBuilder {
        // Use Transaction.newBuilder() to construct.
        private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Transaction() {
            data_ = com.google.protobuf.ByteString.EMPTY;
            pubkey_ = com.google.protobuf.ByteString.EMPTY;
            sign_ = com.google.protobuf.ByteString.EMPTY;
            result_ = com.google.protobuf.ByteString.EMPTY;
            extra_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private Transaction(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            chain.tj.model.proto.MyTransaction.TransactionHeader.Builder subBuilder = null;
                            if (header_ != null) {
                                subBuilder = header_.toBuilder();
                            }
                            header_ = input.readMessage(chain.tj.model.proto.MyTransaction.TransactionHeader.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(header_);
                                header_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {

                            data_ = input.readBytes();
                            break;
                        }
                        case 26: {

                            pubkey_ = input.readBytes();
                            break;
                        }
                        case 34: {

                            sign_ = input.readBytes();
                            break;
                        }
                        case 42: {

                            result_ = input.readBytes();
                            break;
                        }
                        case 50: {

                            extra_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return chain.tj.model.proto.MyTransaction.internal_static_transaction_Transaction_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return chain.tj.model.proto.MyTransaction.internal_static_transaction_Transaction_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            chain.tj.model.proto.MyTransaction.Transaction.class, chain.tj.model.proto.MyTransaction.Transaction.Builder.class);
        }

        public static final int HEADER_FIELD_NUMBER = 1;
        private chain.tj.model.proto.MyTransaction.TransactionHeader header_;

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        public boolean hasHeader() {
            return header_ != null;
        }

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        public chain.tj.model.proto.MyTransaction.TransactionHeader getHeader() {
            return header_ == null ? chain.tj.model.proto.MyTransaction.TransactionHeader.getDefaultInstance() : header_;
        }

        /**
         * <code>optional .transaction.TransactionHeader header = 1;</code>
         */
        public chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder getHeaderOrBuilder() {
            return getHeader();
        }

        public static final int DATA_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString data_;

        /**
         * <pre>
         * 交易内容
         * </pre>
         *
         * <code>optional bytes data = 2;</code>
         */
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        public static final int PUBKEY_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString pubkey_;

        /**
         * <pre>
         * 发送方公钥
         * </pre>
         *
         * <code>optional bytes pubkey = 3;</code>
         */
        public com.google.protobuf.ByteString getPubkey() {
            return pubkey_;
        }

        public static final int SIGN_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString sign_;

        /**
         * <pre>
         * 签名
         * </pre>
         *
         * <code>optional bytes sign = 4;</code>
         */
        public com.google.protobuf.ByteString getSign() {
            return sign_;
        }

        public static final int RESULT_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString result_;

        /**
         * <code>optional bytes result = 5;</code>
         */
        public com.google.protobuf.ByteString getResult() {
            return result_;
        }

        public static final int EXTRA_FIELD_NUMBER = 6;
        private com.google.protobuf.ByteString extra_;

        /**
         * <code>optional bytes extra = 6;</code>
         */
        public com.google.protobuf.ByteString getExtra() {
            return extra_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (header_ != null) {
                output.writeMessage(1, getHeader());
            }
            if (!data_.isEmpty()) {
                output.writeBytes(2, data_);
            }
            if (!pubkey_.isEmpty()) {
                output.writeBytes(3, pubkey_);
            }
            if (!sign_.isEmpty()) {
                output.writeBytes(4, sign_);
            }
            if (!result_.isEmpty()) {
                output.writeBytes(5, result_);
            }
            if (!extra_.isEmpty()) {
                output.writeBytes(6, extra_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (header_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getHeader());
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, data_);
            }
            if (!pubkey_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, pubkey_);
            }
            if (!sign_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, sign_);
            }
            if (!result_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, result_);
            }
            if (!extra_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(6, extra_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof chain.tj.model.proto.MyTransaction.Transaction)) {
                return super.equals(obj);
            }
            chain.tj.model.proto.MyTransaction.Transaction other = (chain.tj.model.proto.MyTransaction.Transaction) obj;

            boolean result = true;
            result = result && (hasHeader() == other.hasHeader());
            if (hasHeader()) {
                result = result && getHeader()
                        .equals(other.getHeader());
            }
            result = result && getData()
                    .equals(other.getData());
            result = result && getPubkey()
                    .equals(other.getPubkey());
            result = result && getSign()
                    .equals(other.getSign());
            result = result && getResult()
                    .equals(other.getResult());
            result = result && getExtra()
                    .equals(other.getExtra());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptorForType().hashCode();
            if (hasHeader()) {
                hash = (37 * hash) + HEADER_FIELD_NUMBER;
                hash = (53 * hash) + getHeader().hashCode();
            }
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
            hash = (53 * hash) + getPubkey().hashCode();
            hash = (37 * hash) + SIGN_FIELD_NUMBER;
            hash = (53 * hash) + getSign().hashCode();
            hash = (37 * hash) + RESULT_FIELD_NUMBER;
            hash = (53 * hash) + getResult().hashCode();
            hash = (37 * hash) + EXTRA_FIELD_NUMBER;
            hash = (53 * hash) + getExtra().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static chain.tj.model.proto.MyTransaction.Transaction parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(chain.tj.model.proto.MyTransaction.Transaction prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code transaction.Transaction}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:transaction.Transaction)
                chain.tj.model.proto.MyTransaction.TransactionOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_Transaction_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_Transaction_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                chain.tj.model.proto.MyTransaction.Transaction.class, chain.tj.model.proto.MyTransaction.Transaction.Builder.class);
            }

            // Construct using chain.tj.model.proto.MyTransaction.Transaction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                if (headerBuilder_ == null) {
                    header_ = null;
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }
                data_ = com.google.protobuf.ByteString.EMPTY;

                pubkey_ = com.google.protobuf.ByteString.EMPTY;

                sign_ = com.google.protobuf.ByteString.EMPTY;

                result_ = com.google.protobuf.ByteString.EMPTY;

                extra_ = com.google.protobuf.ByteString.EMPTY;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return chain.tj.model.proto.MyTransaction.internal_static_transaction_Transaction_descriptor;
            }

            public chain.tj.model.proto.MyTransaction.Transaction getDefaultInstanceForType() {
                return chain.tj.model.proto.MyTransaction.Transaction.getDefaultInstance();
            }

            public chain.tj.model.proto.MyTransaction.Transaction build() {
                chain.tj.model.proto.MyTransaction.Transaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public chain.tj.model.proto.MyTransaction.Transaction buildPartial() {
                chain.tj.model.proto.MyTransaction.Transaction result = new chain.tj.model.proto.MyTransaction.Transaction(this);
                if (headerBuilder_ == null) {
                    result.header_ = header_;
                } else {
                    result.header_ = headerBuilder_.build();
                }
                result.data_ = data_;
                result.pubkey_ = pubkey_;
                result.sign_ = sign_;
                result.result_ = result_;
                result.extra_ = extra_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof chain.tj.model.proto.MyTransaction.Transaction) {
                    return mergeFrom((chain.tj.model.proto.MyTransaction.Transaction) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(chain.tj.model.proto.MyTransaction.Transaction other) {
                if (other == chain.tj.model.proto.MyTransaction.Transaction.getDefaultInstance()) return this;
                if (other.hasHeader()) {
                    mergeHeader(other.getHeader());
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                if (other.getPubkey() != com.google.protobuf.ByteString.EMPTY) {
                    setPubkey(other.getPubkey());
                }
                if (other.getSign() != com.google.protobuf.ByteString.EMPTY) {
                    setSign(other.getSign());
                }
                if (other.getResult() != com.google.protobuf.ByteString.EMPTY) {
                    setResult(other.getResult());
                }
                if (other.getExtra() != com.google.protobuf.ByteString.EMPTY) {
                    setExtra(other.getExtra());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                chain.tj.model.proto.MyTransaction.Transaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (chain.tj.model.proto.MyTransaction.Transaction) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private chain.tj.model.proto.MyTransaction.TransactionHeader header_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    chain.tj.model.proto.MyTransaction.TransactionHeader, chain.tj.model.proto.MyTransaction.TransactionHeader.Builder, chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder> headerBuilder_;

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public boolean hasHeader() {
                return headerBuilder_ != null || header_ != null;
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public chain.tj.model.proto.MyTransaction.TransactionHeader getHeader() {
                if (headerBuilder_ == null) {
                    return header_ == null ? chain.tj.model.proto.MyTransaction.TransactionHeader.getDefaultInstance() : header_;
                } else {
                    return headerBuilder_.getMessage();
                }
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public Builder setHeader(chain.tj.model.proto.MyTransaction.TransactionHeader value) {
                if (headerBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    header_ = value;
                    onChanged();
                } else {
                    headerBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public Builder setHeader(
                    chain.tj.model.proto.MyTransaction.TransactionHeader.Builder builderForValue) {
                if (headerBuilder_ == null) {
                    header_ = builderForValue.build();
                    onChanged();
                } else {
                    headerBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public Builder mergeHeader(chain.tj.model.proto.MyTransaction.TransactionHeader value) {
                if (headerBuilder_ == null) {
                    if (header_ != null) {
                        header_ =
                                chain.tj.model.proto.MyTransaction.TransactionHeader.newBuilder(header_).mergeFrom(value).buildPartial();
                    } else {
                        header_ = value;
                    }
                    onChanged();
                } else {
                    headerBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public Builder clearHeader() {
                if (headerBuilder_ == null) {
                    header_ = null;
                    onChanged();
                } else {
                    header_ = null;
                    headerBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public chain.tj.model.proto.MyTransaction.TransactionHeader.Builder getHeaderBuilder() {

                onChanged();
                return getHeaderFieldBuilder().getBuilder();
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            public chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder getHeaderOrBuilder() {
                if (headerBuilder_ != null) {
                    return headerBuilder_.getMessageOrBuilder();
                } else {
                    return header_ == null ?
                            chain.tj.model.proto.MyTransaction.TransactionHeader.getDefaultInstance() : header_;
                }
            }

            /**
             * <code>optional .transaction.TransactionHeader header = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    chain.tj.model.proto.MyTransaction.TransactionHeader, chain.tj.model.proto.MyTransaction.TransactionHeader.Builder, chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder>
            getHeaderFieldBuilder() {
                if (headerBuilder_ == null) {
                    headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            chain.tj.model.proto.MyTransaction.TransactionHeader, chain.tj.model.proto.MyTransaction.TransactionHeader.Builder, chain.tj.model.proto.MyTransaction.TransactionHeaderOrBuilder>(
                            getHeader(),
                            getParentForChildren(),
                            isClean());
                    header_ = null;
                }
                return headerBuilder_;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 交易内容
             * </pre>
             *
             * <code>optional bytes data = 2;</code>
             */
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <pre>
             * 交易内容
             * </pre>
             *
             * <code>optional bytes data = 2;</code>
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                data_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 交易内容
             * </pre>
             *
             * <code>optional bytes data = 2;</code>
             */
            public Builder clearData() {

                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString pubkey_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 发送方公钥
             * </pre>
             *
             * <code>optional bytes pubkey = 3;</code>
             */
            public com.google.protobuf.ByteString getPubkey() {
                return pubkey_;
            }

            /**
             * <pre>
             * 发送方公钥
             * </pre>
             *
             * <code>optional bytes pubkey = 3;</code>
             */
            public Builder setPubkey(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                pubkey_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 发送方公钥
             * </pre>
             *
             * <code>optional bytes pubkey = 3;</code>
             */
            public Builder clearPubkey() {

                pubkey_ = getDefaultInstance().getPubkey();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString sign_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 签名
             * </pre>
             *
             * <code>optional bytes sign = 4;</code>
             */
            public com.google.protobuf.ByteString getSign() {
                return sign_;
            }

            /**
             * <pre>
             * 签名
             * </pre>
             *
             * <code>optional bytes sign = 4;</code>
             */
            public Builder setSign(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                sign_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 签名
             * </pre>
             *
             * <code>optional bytes sign = 4;</code>
             */
            public Builder clearSign() {

                sign_ = getDefaultInstance().getSign();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes result = 5;</code>
             */
            public com.google.protobuf.ByteString getResult() {
                return result_;
            }

            /**
             * <code>optional bytes result = 5;</code>
             */
            public Builder setResult(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                result_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes result = 5;</code>
             */
            public Builder clearResult() {

                result_ = getDefaultInstance().getResult();
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString extra_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>optional bytes extra = 6;</code>
             */
            public com.google.protobuf.ByteString getExtra() {
                return extra_;
            }

            /**
             * <code>optional bytes extra = 6;</code>
             */
            public Builder setExtra(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                extra_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes extra = 6;</code>
             */
            public Builder clearExtra() {

                extra_ = getDefaultInstance().getExtra();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:transaction.Transaction)
        }

        // @@protoc_insertion_point(class_scope:transaction.Transaction)
        private static final chain.tj.model.proto.MyTransaction.Transaction DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new chain.tj.model.proto.MyTransaction.Transaction();
        }

        public static chain.tj.model.proto.MyTransaction.Transaction getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Transaction>
                PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
            public Transaction parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Transaction(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Transaction> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Transaction> getParserForType() {
            return PARSER;
        }

        public chain.tj.model.proto.MyTransaction.Transaction getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_transaction_TransactionHeader_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_transaction_TransactionHeader_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_transaction_Transaction_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_transaction_Transaction_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021transaction.proto\022\013transaction\"o\n\021Tran" +
                        "sactionHeader\022\017\n\007version\030\001 \001(\r\022\014\n\004type\030\002" +
                        " \001(\r\022\017\n\007subType\030\003 \001(\r\022\021\n\ttimestamp\030\004 \001(\004" +
                        "\022\027\n\017transactionHash\030\005 \001(\014\"\210\001\n\013Transactio" +
                        "n\022.\n\006header\030\001 \001(\0132\036.transaction.Transact" +
                        "ionHeader\022\014\n\004data\030\002 \001(\014\022\016\n\006pubkey\030\003 \001(\014\022" +
                        "\014\n\004sign\030\004 \001(\014\022\016\n\006result\030\005 \001(\014\022\r\n\005extra\030\006" +
                        " \001(\014B(\n\024chain.tj.model.protoB\rMyTransact" +
                        "ion\210\001\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_transaction_TransactionHeader_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_transaction_TransactionHeader_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_transaction_TransactionHeader_descriptor,
                new java.lang.String[]{"Version", "Type", "SubType", "Timestamp", "TransactionHash",});
        internal_static_transaction_Transaction_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_transaction_Transaction_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_transaction_Transaction_descriptor,
                new java.lang.String[]{"Header", "Data", "Pubkey", "Sign", "Result", "Extra",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
